server:
  port: 8086

spring:
  application:
    name: notification-service
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: notification-service-group
      # Khai báo rõ Deserializer để xử lý JSON và bắt lỗi
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        # Chỉ định class mặc định để map dữ liệu JSON
        spring.json.value.default.type: com.cameraclick.notification.event.OrderCreatedEvent
  mail:
    host: smtp.gmail.com
    port: 587
    username: nguyentanthien12032005@gmail.com
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    com.fashionstore.notification: DEBUG